config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { invitations: 'users/invitations' }

  root to: 'pages#home'

  resource :dashboard, only: [:show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :cuisine_events, only: [:new, :create]
  get 'kitchensink', to: 'pages#kitchensink'
  get 'test', to: 'pages#test'

  resources :events, only: [] do
    namespace :invitations do
      resources :attendences, only: [:create, :destroy]
    end
  end

  # resources :events, param: :hash_token, only: [:new, :create, :show, :index] do
  resources :restaurants, only: :create
  resources :events, only: [:new, :create, :show, :index] do
    resources :mass_invitations, only: [:create]
    resources :invitations, only: [:new, :create, :show]
    resources :cuisine_events, only: [:create]
    resources :results, only: [:new, :create, :show]
    post 'invite', to: 'events#invite'
  end
end

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_invited.html.erb
<% if @result %>
 <% event.invitations.each do |invitation| %>
    <% if invitation.status == "Confirmed" %>
      <div class="notification mr-4">
        <div class="marker">
          <h3><%= invitation.user.name[0].capitalize %></h3>
        </div>
        <div class="notification-content text-break">
          <p><small><%= invitation.user.name %></small></p>
        </div>
      </div>
    <% end %>
  <% end %>

<% else %>
  <% event.invitations.each do |invitation| %>
    <% if invitation.cancelled? %>
      <div class="notification mr-4">
        <div class="marker cancelled">
          <h3><%= invitation.user.name[0].capitalize %></h3>
        </div>
        <div class="notification-content text-break">
          <p><small><%= invitation.user.name %></small></p>
        </div>
      </div>
    <% else %>
      <div class="notification mr-4">
        <div class="marker">
          <h3><%= invitation.user.name[0].capitalize %></h3>
        </div>
        <div class="notification-content text-break">
          <p><small><%= invitation.user.name %></small></p>
        </div>
      </div>
    <% end %>
  <% end %>

  <% event.users_pending_invitation.each do |user| %>
    <div class="notification mr-4">
      <div class="marker avatar-large-pending">
        <h3><%= user.name[0].capitalize %></h3>
      </div>
      <div class="notification-content text-break">
        <p><small><%= user.name %></small></p>
      </div>
    </div>
  <% end %>

<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand navbar-light navbar-lewagon">
  <div class="container">
  <% img = image_tag("logo.png") %>

   <%= image_tag "logo.png", class: "navbar-brand", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
   <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdown">
          <% if user_signed_in? %>
            <%= link_to "Home", "/", class: "dropdown-item" %>
            <%= link_to "Your events", events_path, class: "dropdown-item" %>
            <%= link_to "Create new event", new_event_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            <% else %>
            <%= link_to "Log in", new_user_session_path, class: "dropdown-item" %>
          <% end %>
        </div>

  </div>
</div>

app/views/shared/_navbar_basic.html.erb
<%= link_to image_tag("logo-crop.png", class: "logo-body mb-4"), "/" %>

app/views/shared/_navbar_logo_plus.html.erb
<div class="row d-flex justify-content-between align-center" style="padding-left: 15px; padding-right: 15px;">
  <%= link_to image_tag("logo-crop.png", class: "logo-body mb-4"), "/" %>
  <%= link_to image_tag("circle-add.png", class: "plus-body mb-4"), new_event_path %>
</div>