config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { invitations: 'users/invitations' }

  root to: 'pages#home'

  resource :dashboard, only: [:show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :cuisine_events, only: [:new, :create]
  get 'kitchensink', to: 'pages#kitchensink'
  get 'test', to: 'pages#test'

  resources :events, only: [] do
    namespace :invitations do
      resources :attendences, only: [:create, :destroy]
    end
  end

  # resources :events, param: :hash_token, only: [:new, :create, :show, :index] do
  resources :restaurants, only: :create
  resources :events, only: [:new, :create, :show, :index] do
    resources :mass_invitations, only: [:create]
    resources :invitations, only: [:new, :create, :show]
    resources :cuisine_events, only: [:create]
    resources :results, only: [:new, :create, :show]
    post 'invite', to: 'events#invite'
  end
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :invitations
  has_many :users, through: :invitations
  has_one :result
  has_one :restaurant, through: :results
  has_many :cuisine_events
  has_many :cuisines, through: :cuisine_events
  validates :name, :start_at, presence: true
  validates :hash_token, presence: true
  validates :hash_token, uniqueness: true

  before_validation :generate_hash_token

  def invited_users
    relation_a = User.where(last_event: id).to_a
    relation_b = users.to_a
    (relation_a + relation_b).uniq(&:id)
  end

  def users_pending_invitation
    User.where(last_event: id, invitation_accepted_at: nil)
  end

  def generate_hash_token
    begin
      self.hash_token = SecureRandom.urlsafe_base64(24, false)
    end while self.class.exists?(hash_token: hash_token)
  end

  def to_param
    token
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show]

  def new
    @event = Event.new
    @cuisine_event = CuisineEvent.new
    @event.invitations.build
  end

  def index
    @events = Event.all
    @user = current_user
    @user_invitations = Invitation.where(user: @user)
  end

  def create
    unless event_params[:cuisine_event_ids].present?
      flash[:alert] = "Please pick a type of food!"
      redirect_to new_event_path and return
    end
    @event = Event.new(event_params.except(:cuisine_event_ids))
    @event.decided = false
    if @event.save
      cuisine_event_params(event_params)
      redirect_to new_event_invitation_path(@event)
    else
      render :new
    end
  end

  def show
    # @invitation = Invitation.new
    @user = current_user
    @invitation = @user.invitations.find_by(event:@event)
    if @event.result
      redirect_to event_result_path(@event, @event.result) and return
    else
      @markers = @event.invitations.where(status:"Confirmed").map do |i|
        {
          lat: i.latitude,
          lng: i.longitude,
          infoWindow: i.user.email[0].capitalize,
          # infoWindow: render_to_string(partial: "infowindow", locals: { flat: flat }),
          image_url: helpers.asset_url('map-user-blue.png')
        }
      end
    end
  end

  def invite
    @user = User.find_by({ email: email_params[:invite][:email].downcase })
    @event = Event.find(params[:event_id])
    raise
    if @user.present? && @user.email == current_user.email.downcase
      flash[:alert] = "You're already attending this event"
    elsif @event.users.include?(@user) || @event.users_pending_invitation.include?(@user)
      flash[:alert] = "You've already invited #{@user.email}"
    elsif @user.present?
      @user.last_event = @event.id
      @user.invite!
      flash[:alert] = "Your invitation has been sent!!!"
      event_channel
    else
      flash[:alert] = "Your invitation has been sent!"
      User.invite!(email: email_params[:invite][:email].downcase, last_event: @event.id)
      @event.reload
      event_channel
    end
    redirect_to event_path(@event)
  end

  private

  def cuisine_event_params(event_params)
    @save_count = 0
    event_params[:cuisine_event_ids].each do |id|
      @cuisine_event = CuisineEvent.new
      @cuisine = Cuisine.find(id.to_i)
      @cuisine_event.cuisine = @cuisine
      @cuisine_event.event = @event
      @cuisine_event.save!
      @save_count += 1
    end
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :description, :start_at, cuisine_event_ids: [])
  end

  def create_invitations
    @event = Event.find(params[:id])
    @invitation = Invitation.new
  end

  def email_params
    params.permit(invite: :email)
  end

  def event_channel
    EventChannel.broadcast_to(
      @event,
      render_to_string(partial: "shared/invited", locals: { event: @event })
    )
  end
end

app/views/events/index.html.erb
<div class = "container mt-4 event-index">
  <%= render 'shared/navbar_logo_plus' %>
  <% @user_invitations.each do |i| %>
    <div class="border border-white p-3 rounded-lg mb-4">
      <h4><%= link_to i.event.name, event_path(i.event.id), style: "color: white;" %></h4>
      <p><%= i.event.description %></p>
      <h6><em>On <%= i.event.start_at.strftime("%A, %b %d") %> at </i><%= i.event.start_at.strftime("%I:%M %P") %></em></h6>
    </div>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<div class="container mt-4 event-index">
  <%= render 'shared/navbar_basic' %>
</div>

<% img = image_tag("logo.png") %>
<div class="div-shape-sm">
  <div class="container">
    <h2 class = "banner">Let's party! 🎉</h2>
  </div>
</div>

<div class="container">
  <%= simple_form_for(@event, html: {class: "mt-4 mb-4"}) do |f| %>
      <div class="form-inputs">
      <%= f.input :name, label: "What's happening?" , input_html: {maxlength: 24, size: 40}, placeholder: "Give your event a name",:label_html => { :class => 'label' }, :wrapper_html => { class: "icon-field"}, required: :true %>

        <%= f.association :cuisine_events, :label => "What food is everyone into?", collection: Cuisine.all, input_html: { multiple: true, data: {:placeholder => '100\'s of cuisines'} }, include_hidden: false, :label_html => { :class => 'label'},:wrapper_html => { class: "icon-field"}, required: :true %>

        <%= f.input :description, label: "What's the occasion?",input_html: {maxlength: 60, size: 100}, placeholder: "Add a comment for your friends!",:label_html => { :class => 'label' }, :wrapper_html => { class: "icon-field"} %>

        <%= f.input :start_at, label: "When's this happening?", as: :datetime, html5: true, placeholder: "Add a comment for your friends!", :label_html => { :class => 'label' }, :wrapper_html => { class: "icon-field"}, input_html: {min: Date.today}%>
      </div>
      <div class="form-actions mt-4 mb-4">
          <%= f.button :submit, "Next", class:" submit" %>
      </div>
  <% end %>
</div>

app/views/events/show.html.erb
<div class="mobile-frame row">
  <div class="col-md-6">
    <div class="map-event">
      <div id="map" style="height: 100vh;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
    </div>
  </div>
  <div class="event-content col-md-6">
    <div class="bgc-event">
      <div class="container pt-3">
        <%= link_to image_tag("logo-crop.png", class: "logo-body mb-3"), "/" %>
        <h2 class="mb-3"><strong><%= @event.name %></strong></h2>
        <h6><em>On <%= @event.start_at.strftime("%A, %b %d") %> at </i><%= @event.start_at.strftime("%I:%M %P") %></em></h6>
        <p class="mb-4"><%= @event.description %></p>
        <h6 class="mb-3"><strong>Invite friends</strong></h6>
        <h6>INVITE LINK</h6>
        <%= simple_form_for(:invite, url: event_invite_path(@event), method: :post, remote: true) do |f| %>
          <%= f.input :email, label: false, wrapper_html: {class: "d-flex justify-content-between"} do %>
            <%= f.input_field :email, as: :email, placeholder: "  Friend's email address", class: "email-input-form" %>
            <%= f.button :submit, '+',id: "js-friend-email-btn" ,class: "email-input-btn", label_html: { class: 'input-group-append'} %>
          <% end %>
        <% end %>
        <h6 class="mb-3"><strong>Who's coming</strong></h6>
        <div class="d-flex notification-container mb-3" id="invite-container" data-event-id="<%= @event.id %>">
            <%= render 'shared/invited', event:@event %>
        </div>

        <%= simple_form_for(:result, url:event_results_path(@event)) do |f| %>
          <%= f.button :submit, value:"Decide!", class: "js-sweetalert btn btn-block d-btn-light p-2"%>
        <% end %>
        <% if @invitation.cancelled? %>
          <%= link_to "Want to attend?", event_invitations_attendences_path(@event.id), class: "btn btn-block d-btn-transparent p-2 mt-3", method: :post %>
        <% else %>
          <%= link_to "Can't come?", event_invitations_attendence_path(@event.id), class: "btn btn-block d-btn-transparent p-2 mt-3", method: :delete %>
        <% end %>
      </div>
    </div>
  </div>
</div>